"""Implementation modules for AIVM's desired-state config store."""

from .io import (
    ConfigSource,
    LoadedStore,
    is_split_layout,
    load_config_document,
    load_store,
    render_split_fragments,
    save_store,
    save_store_split,
    format_existing_config,
    split_fragment_paths,
    split_source_paths,
)
from .models import AttachmentEntry, NetworkEntry, Store, VMEntry
from .parse import parse_store_toml
from .mutate import (
    remove_attachment,
    remove_network,
    remove_vm,
    upsert_attachment,
    upsert_network,
    upsert_vm,
    upsert_vm_with_network,
)
from .paths import app_data_dir, app_data_path, persistent_host_state_dir, store_path
from .render import (
    render_store_defaults_toml,
    render_store_networks_toml,
    render_store_root_toml,
    render_store_toml,
    render_store_vm_toml,
)
from .resolve import (
    find_attachment,
    find_attachment_for_vm,
    find_attachments,
    find_attachments_for_vm,
    find_network,
    find_vm,
    materialize_vm_cfg,
    network_users,
)

__all__ = [
    'AttachmentEntry',
    'split_source_paths',
    'load_config_document',
    'is_split_layout',
    'LoadedStore',
    'ConfigSource',
    'NetworkEntry',
    'Store',
    'VMEntry',
    'app_data_dir',
    'app_data_path',
    'find_attachment',
    'find_attachment_for_vm',
    'find_attachments',
    'find_attachments_for_vm',
    'find_network',
    'find_vm',
    'load_store',
    'materialize_vm_cfg',
    'network_users',
    'parse_store_toml',
    'persistent_host_state_dir',
    'remove_attachment',
    'remove_network',
    'remove_vm',
    'render_split_fragments',
    'save_store_split',
    'format_existing_config',
    'split_fragment_paths',
    'render_store_defaults_toml',
    'render_store_networks_toml',
    'render_store_root_toml',
    'render_store_vm_toml',
    'render_store_toml',
    'save_store',
    'store_path',
    'upsert_attachment',
    'upsert_network',
    'upsert_vm',
    'upsert_vm_with_network',
]
