"""Install and reconcile repository credentials inside an AIVM guest."""

from __future__ import annotations

import shlex

from ..commands import CommandHandle, CommandManager, CommandResult
from ..config import AgentVMConfig
from ..config_store import CredentialEntry
from ..runtime import require_ssh_identity, ssh_base_args
from .models import GitRepository

_GUEST_ROOT = '.local/share/aivm/credentials'
_SSH_MANAGED = '.ssh/aivm.d/credentials.conf'
_GIT_MANAGED = '.config/aivm/gitconfig-credentials'
_SSH_INCLUDE = 'Include ~/.ssh/aivm.d/*.conf'
_GIT_INCLUDE = '~/.config/aivm/gitconfig-credentials'


def guest_private_key_relpath(cred_id: str) -> str:
    return f'{_GUEST_ROOT}/{cred_id}/id_ed25519'


def _ssh_command(cfg: AgentVMConfig, ip: str, script: str) -> list[str]:
    ident = require_ssh_identity(cfg.paths.ssh_identity_file)
    return [
        'ssh',
        *ssh_base_args(
            ident,
            strict_host_key_checking='accept-new',
            connect_timeout=15,
            batch_mode=True,
        ),
        f'{cfg.vm.user}@{ip}',
        script,
    ]


def _submit_guest(
    cfg: AgentVMConfig,
    ip: str,
    *,
    script: str,
    manager: CommandManager,
    role: str,
    summary: str,
    input_text: str | None = None,
    check: bool = True,
) -> CommandHandle:
    return manager.submit(
        _ssh_command(cfg, ip, script),
        sudo=False,
        role='read' if role == 'read' else 'modify',
        check=check,
        capture=True,
        input_text=input_text,
        summary=summary,
    )


def _run_guest(
    cfg: AgentVMConfig,
    ip: str,
    *,
    script: str,
    manager: CommandManager,
    role: str,
    summary: str,
    input_text: str | None = None,
    check: bool = True,
) -> CommandResult:
    return _submit_guest(
        cfg,
        ip,
        script=script,
        manager=manager,
        role=role,
        summary=summary,
        input_text=input_text,
        check=check,
    ).result()


def _install_guest_file(
    cfg: AgentVMConfig,
    ip: str,
    *,
    relpath: str,
    text: str,
    mode: str,
    manager: CommandManager,
    label: str,
) -> None:
    rel_q = shlex.quote(relpath)
    mode_q = shlex.quote(mode)
    script = (
        'set -eu; umask 077; '
        f'target="$HOME"/{rel_q}; '
        'mkdir -p "$(dirname "$target")"; '
        'tmp="$(mktemp)"; '
        'cat > "$tmp"; '
        f'chmod {mode_q} "$tmp"; '
        'mv "$tmp" "$target"'
    )
    _submit_guest(
        cfg,
        ip,
        script=script,
        manager=manager,
        role='modify',
        summary=f'Install guest {label}',
        input_text=text,
    )


def render_ssh_config(credentials: list[CredentialEntry]) -> str:
    lines = ['# Managed by aivm. Do not edit this file directly.']
    for cred in sorted(credentials, key=lambda item: item.id):
        alias = f'aivm-cred-{cred.id}'
        key_path = '~/' + guest_private_key_relpath(cred.id)
        lines.extend(
            [
                '',
                f'Host {alias}',
                f'    HostName {cred.provider_host}',
                f'    HostKeyAlias {cred.provider_host}',
                '    User git',
                f'    IdentityFile {key_path}',
                '    IdentitiesOnly yes',
            ]
        )
    return '\n'.join(lines).rstrip() + '\n'


def render_git_config(credentials: list[CredentialEntry]) -> str:
    lines = ['# Managed by aivm. Do not edit this file directly.']
    for cred in sorted(credentials, key=lambda item: item.id):
        alias = f'aivm-cred-{cred.id}'
        repo_path = f'{cred.owner}/{cred.repository}'
        target = f'git@{alias}:{repo_path}.git'
        source_urls = [
            f'git@{cred.provider_host}:{repo_path}.git',
            f'git@{cred.provider_host}:{repo_path}',
            f'ssh://git@{cred.provider_host}/{repo_path}.git',
            f'ssh://git@{cred.provider_host}/{repo_path}',
            f'https://{cred.provider_host}/{repo_path}.git',
            f'https://{cred.provider_host}/{repo_path}',
        ]
        lower = [url.lower() for url in source_urls]
        source_urls.extend(url for url in lower if url not in source_urls)
        lines.extend(['', f'[url "{target}"]'])
        lines.extend(f'    insteadOf = {url}' for url in source_urls)
    return '\n'.join(lines).rstrip() + '\n'


def _ensure_guest_includes(
    cfg: AgentVMConfig, ip: str, *, manager: CommandManager
) -> None:
    ssh_include_q = shlex.quote(_SSH_INCLUDE)
    git_include_q = shlex.quote(_GIT_INCLUDE)
    script = (
        'set -eu; umask 077; '
        'mkdir -p "$HOME/.ssh/aivm.d" "$HOME/.config/aivm"; '
        'touch "$HOME/.ssh/config"; chmod 600 "$HOME/.ssh/config"; '
        f'if ! grep -Fqx {ssh_include_q} "$HOME/.ssh/config"; then '
        'tmp="$(mktemp)"; '
        f'printf "%s\\n" {ssh_include_q} > "$tmp"; '
        'cat "$HOME/.ssh/config" >> "$tmp"; '
        'mv "$tmp" "$HOME/.ssh/config"; chmod 600 "$HOME/.ssh/config"; fi; '
        'if ! git config --global --get-all include.path 2>/dev/null '
        f'| grep -Fqx {git_include_q}; then '
        f'git config --global --add include.path {git_include_q}; fi'
    )
    _submit_guest(
        cfg,
        ip,
        script=script,
        manager=manager,
        role='modify',
        summary='Enable AIVM-managed SSH and Git credential includes',
    )


def reconcile_guest_credentials(
    cfg: AgentVMConfig,
    ip: str,
    *,
    credentials: list[CredentialEntry],
    private_key: tuple[str, str] | None,
    remove_credential_id: str = '',
    manager: CommandManager,
) -> None:
    """Install one key and regenerate all AIVM-managed guest config."""
    with manager.step(
        'Reconcile VM repository credentials',
        why='Install scoped keys and regenerate AIVM-managed Git/SSH config.',
        approval_scope=f'vm-credentials:{cfg.vm.name}',
    ):
        if private_key is not None:
            cred_id, key_text = private_key
            _install_guest_file(
                cfg,
                ip,
                relpath=guest_private_key_relpath(cred_id),
                text=key_text,
                mode='600',
                manager=manager,
                label=f'private deploy key {cred_id}',
            )
        _install_guest_file(
            cfg,
            ip,
            relpath=_SSH_MANAGED,
            text=render_ssh_config(credentials),
            mode='600',
            manager=manager,
            label='managed SSH credential config',
        )
        _install_guest_file(
            cfg,
            ip,
            relpath=_GIT_MANAGED,
            text=render_git_config(credentials),
            mode='600',
            manager=manager,
            label='managed Git credential config',
        )
        _ensure_guest_includes(cfg, ip, manager=manager)
        if remove_credential_id:
            rel_q = shlex.quote(f'{_GUEST_ROOT}/{remove_credential_id}')
            _submit_guest(
                cfg,
                ip,
                script=f'set -eu; rm -rf -- "$HOME"/{rel_q}',
                manager=manager,
                role='modify',
                summary=f'Remove guest credential {remove_credential_id}',
            )


def verify_guest_repository(
    cfg: AgentVMConfig,
    ip: str,
    repo: GitRepository,
    *,
    manager: CommandManager,
) -> CommandResult:
    command = f'git ls-remote {shlex.quote(repo.https_url)} HEAD'
    return _run_guest(
        cfg,
        ip,
        script=command,
        manager=manager,
        role='read',
        summary=f'Verify guest Git access to {repo.display}',
        check=False,
    )


def read_guest_public_key(
    cfg: AgentVMConfig,
    ip: str,
    cred_id: str,
    *,
    manager: CommandManager,
) -> CommandResult:
    rel_q = shlex.quote(guest_private_key_relpath(cred_id))
    return _run_guest(
        cfg,
        ip,
        script=f'ssh-keygen -y -f "$HOME"/{rel_q}',
        manager=manager,
        role='read',
        summary=f'Inspect guest deploy key {cred_id}',
        check=False,
    )
