"""Install and reconcile repository credentials inside an AIVM guest."""

from __future__ import annotations

import shlex

from ..commands import CommandHandle, CommandManager, CommandResult
from ..config import AgentVMConfig
from ..config_store import CredentialEntry
from ..runtime import require_ssh_identity, ssh_base_args
from .models import GitRepository
from .validation import (
    CredentialValidationError,
    validate_credential_id_format,
    validate_credential_identity,
)

_GUEST_ROOT = '.local/share/aivm/credentials'
_SSH_MANAGED = '.ssh/aivm.d/credentials.conf'
_GIT_MANAGED = '.config/aivm/gitconfig-credentials'
_SSH_INCLUDE = 'Include ~/.ssh/aivm.d/*.conf'
_GIT_INCLUDE = '~/.config/aivm/gitconfig-credentials'


def _safe_credential_id(cred_id: str) -> str:
    try:
        return validate_credential_id_format(cred_id)
    except CredentialValidationError as ex:
        from ..errors import AIVMError

        raise AIVMError(str(ex)) from ex


def guest_private_key_relpath(cred_id: str) -> str:
    safe_id = _safe_credential_id(cred_id)
    return f'{_GUEST_ROOT}/{safe_id}/id_ed25519'


def guest_credential_dir_relpath(cred_id: str) -> str:
    safe_id = _safe_credential_id(cred_id)
    return f'{_GUEST_ROOT}/{safe_id}'


def _validated_entry_repository(cred: CredentialEntry) -> GitRepository:
    try:
        return validate_credential_identity(
            vm_name=cred.vm_name,
            cred_id=cred.id,
            provider_host=cred.provider_host,
            owner=cred.owner,
            repository=cred.repository,
        )
    except CredentialValidationError as ex:
        from ..errors import AIVMError

        raise AIVMError(str(ex)) from ex


def _ssh_command(cfg: AgentVMConfig, ip: str, script: str) -> list[str]:
    ident = require_ssh_identity(cfg.paths.ssh_identity_file)
    return [
        'ssh',
        *ssh_base_args(
            ident,
            strict_host_key_checking='accept-new',
            connect_timeout=15,
            batch_mode=True,
        ),
        f'{cfg.vm.user}@{ip}',
        script,
    ]


def _submit_guest(
    cfg: AgentVMConfig,
    ip: str,
    *,
    script: str,
    manager: CommandManager,
    role: str,
    summary: str,
    input_text: str | None = None,
    check: bool = True,
) -> CommandHandle:
    return manager.submit(
        _ssh_command(cfg, ip, script),
        sudo=False,
        role='read' if role == 'read' else 'modify',
        check=check,
        capture=True,
        input_text=input_text,
        summary=summary,
    )


def _run_guest(
    cfg: AgentVMConfig,
    ip: str,
    *,
    script: str,
    manager: CommandManager,
    role: str,
    summary: str,
    input_text: str | None = None,
    check: bool = True,
) -> CommandResult:
    return _submit_guest(
        cfg,
        ip,
        script=script,
        manager=manager,
        role=role,
        summary=summary,
        input_text=input_text,
        check=check,
    ).result()


def _install_guest_file(
    cfg: AgentVMConfig,
    ip: str,
    *,
    relpath: str,
    text: str,
    mode: str,
    manager: CommandManager,
    label: str,
) -> None:
    rel_q = shlex.quote(relpath)
    mode_q = shlex.quote(mode)
    script = (
        'set -eu; umask 077; '
        f'target="$HOME"/{rel_q}; '
        'mkdir -p "$(dirname "$target")"; '
        'tmp="$(mktemp)"; '
        'cat > "$tmp"; '
        f'chmod {mode_q} "$tmp"; '
        'mv "$tmp" "$target"'
    )
    _submit_guest(
        cfg,
        ip,
        script=script,
        manager=manager,
        role='modify',
        summary=f'Install guest {label}',
        input_text=text,
    )


def render_ssh_config(credentials: list[CredentialEntry]) -> str:
    lines = ['# Managed by aivm. Do not edit this file directly.']
    for cred in sorted(credentials, key=lambda item: item.id):
        repo = _validated_entry_repository(cred)
        alias = f'aivm-cred-{cred.id}'
        key_path = '~/' + guest_private_key_relpath(cred.id)
        lines.extend(
            [
                '',
                f'Host {alias}',
                f'    HostName {repo.host}',
                f'    HostKeyAlias {repo.host}',
                '    User git',
                f'    IdentityFile {key_path}',
                '    IdentitiesOnly yes',
                '    BatchMode yes',
                '    StrictHostKeyChecking accept-new',
            ]
        )
    return '\n'.join(lines).rstrip() + '\n'


def render_git_config(credentials: list[CredentialEntry]) -> str:
    lines = ['# Managed by aivm. Do not edit this file directly.']
    for cred in sorted(credentials, key=lambda item: item.id):
        repo = _validated_entry_repository(cred)
        alias = f'aivm-cred-{cred.id}'
        repo_path = f'{repo.owner}/{repo.name}'
        target = f'git@{alias}:{repo_path}.git'
        # Git's insteadOf matching is prefix-based, not exact. Restrict
        # rewrites to canonical ``.git`` URLs so granting ``owner/repo`` does
        # not hijack an unrelated sibling such as ``owner/repo-extra``.
        source_urls = [
            f'git@{repo.host}:{repo_path}.git',
            f'ssh://git@{repo.host}/{repo_path}.git',
            f'https://{repo.host}/{repo_path}.git',
        ]
        lower = [url.lower() for url in source_urls]
        source_urls.extend(url for url in lower if url not in source_urls)
        lines.extend(['', f'[url "{target}"]'])
        lines.extend(f'    insteadOf = {url}' for url in source_urls)
    return '\n'.join(lines).rstrip() + '\n'


def _ensure_guest_includes(
    cfg: AgentVMConfig, ip: str, *, manager: CommandManager
) -> None:
    ssh_include_q = shlex.quote(_SSH_INCLUDE)
    git_include_q = shlex.quote(_GIT_INCLUDE)
    script = (
        'set -eu; umask 077; '
        'mkdir -p "$HOME/.ssh/aivm.d" "$HOME/.config/aivm"; '
        'ssh_config="$HOME/.ssh/config"; '
        'if [ -L "$ssh_config" ]; then '
        f'if ! grep -Fqx {ssh_include_q} "$ssh_config" 2>/dev/null; then '
        'printf "%s\\n" '
        '"AIVM refuses to replace symlinked ~/.ssh/config; add the exact managed include to its target or replace the symlink." >&2; '
        'exit 78; fi; '
        'elif [ -e "$ssh_config" ] && [ ! -f "$ssh_config" ]; then '
        'printf "%s\\n" '
        '"AIVM requires ~/.ssh/config to be a regular file." >&2; '
        'exit 78; '
        'else '
        'touch "$ssh_config"; chmod 600 "$ssh_config"; '
        f'if ! grep -Fqx {ssh_include_q} "$ssh_config"; then '
        'tmp="$(mktemp)"; '
        f'printf "%s\\n" {ssh_include_q} > "$tmp"; '
        'cat "$ssh_config" >> "$tmp"; '
        'mv "$tmp" "$ssh_config"; chmod 600 "$ssh_config"; fi; '
        'fi; '
        'if ! git config --global --get-all include.path 2>/dev/null '
        f'| grep -Fqx {git_include_q}; then '
        f'git config --global --add include.path {git_include_q}; fi'
    )
    _submit_guest(
        cfg,
        ip,
        script=script,
        manager=manager,
        role='modify',
        summary='Enable AIVM-managed SSH and Git credential includes',
    )


def reconcile_guest_credentials(
    cfg: AgentVMConfig,
    ip: str,
    *,
    credentials: list[CredentialEntry],
    private_key: tuple[str, str] | None,
    remove_credential_id: str = '',
    manager: CommandManager,
) -> None:
    """Install one key and regenerate all AIVM-managed guest config."""
    with manager.step(
        'Reconcile VM repository credentials',
        why='Install scoped keys and regenerate AIVM-managed Git/SSH config.',
        approval_scope=f'vm-credentials:{cfg.vm.name}',
    ):
        # Refuse an incompatible SSH config before installing private key
        # material. Symlinked configs are accepted only when their referent
        # already contains the exact managed include.
        _ensure_guest_includes(cfg, ip, manager=manager)
        if private_key is not None:
            cred_id, key_text = private_key
            _install_guest_file(
                cfg,
                ip,
                relpath=guest_private_key_relpath(cred_id),
                text=key_text,
                mode='600',
                manager=manager,
                label=f'private deploy key {cred_id}',
            )
        _install_guest_file(
            cfg,
            ip,
            relpath=_SSH_MANAGED,
            text=render_ssh_config(credentials),
            mode='600',
            manager=manager,
            label='managed SSH credential config',
        )
        _install_guest_file(
            cfg,
            ip,
            relpath=_GIT_MANAGED,
            text=render_git_config(credentials),
            mode='600',
            manager=manager,
            label='managed Git credential config',
        )
        if remove_credential_id:
            rel_q = shlex.quote(
                guest_credential_dir_relpath(remove_credential_id)
            )
            _submit_guest(
                cfg,
                ip,
                script=f'set -eu; rm -rf -- "$HOME"/{rel_q}',
                manager=manager,
                role='modify',
                summary=f'Remove guest credential {remove_credential_id}',
            )


def verify_guest_repository(
    cfg: AgentVMConfig,
    ip: str,
    repo: GitRepository,
    credential_id: str,
    *,
    manager: CommandManager,
) -> CommandResult:
    safe_id = _safe_credential_id(credential_id)
    source_url = repo.verification_url
    expected_url = (
        f'git@aivm-cred-{safe_id}:{repo.owner}/{repo.name}.git'
    )
    source_q = shlex.quote(source_url)
    expected_q = shlex.quote(expected_url)
    command = (
        'set -eu; '
        f'resolved="$(git ls-remote --get-url {source_q})"; '
        f'expected={expected_q}; '
        'if [ "$resolved" != "$expected" ]; then '
        'printf "AIVM Git rewrite mismatch: expected %s, got %s\\n" '
        '"$expected" "$resolved" >&2; exit 78; fi; '
        f'GIT_TERMINAL_PROMPT=0 git ls-remote {source_q} HEAD'
    )
    return _run_guest(
        cfg,
        ip,
        script=command,
        manager=manager,
        role='read',
        summary=f'Verify guest Git access to {repo.display}',
        check=False,
    )


def read_guest_public_key(
    cfg: AgentVMConfig,
    ip: str,
    cred_id: str,
    *,
    manager: CommandManager,
) -> CommandResult:
    rel_q = shlex.quote(guest_private_key_relpath(cred_id))
    return _run_guest(
        cfg,
        ip,
        script=f'ssh-keygen -y -f "$HOME"/{rel_q}',
        manager=manager,
        role='read',
        summary=f'Inspect guest deploy key {cred_id}',
        check=False,
    )
