"""Generate and install the virtiofsd wrapper that injects
``--inode-file-handles``.

Why this exists
---------------
The default virtiofsd inode cache holds one host file descriptor per
cached inode. With large persistent-root exports the cumulative FD count
on the host can grow past virtiofsd's NOFILE soft limit, which surfaces
inside the guest as ``OSError(EMFILE)`` from a single
``listdir``/``statx`` call even though the guest process itself has very
few FDs open.

Passing ``--inode-file-handles=prefer`` to virtiofsd switches inode
caching to ``name_to_handle_at`` / ``open_by_handle_at`` — kernel file
handles instead of long-lived FDs — which removes the per-inode FD cost.
``prefer`` is safe on mixed filesystems: any fs that does not support
handles transparently falls back to FD caching.

See ``dev/devcheck/virtiofsd_emfile_findings.md`` for the investigation
that motivated the change.

How aivm uses it
----------------
We do not pass the flag through libvirt XML directly because libvirt does
not expose ``--inode-file-handles`` as a first-class ``<binary>`` child
element. Instead, aivm installs a tiny shell wrapper at
``<base_dir>/virtiofsd-wrapper.sh`` and the domain XML's
``<filesystem>/<binary path='...'>`` points at the wrapper. This is one
shared wrapper per host (lives under ``paths.base_dir``).

The behaviour is controlled by ``Store.behavior.virtiofsd_inode_file_handles``
(persisted in ``[behavior]`` of the global aivm config). Valid values:

  * ``""`` (or anything else) -> no wrapper; emit no ``<binary>`` element.
  * ``"never"``                -> wrapper passes ``--inode-file-handles=never``
                                  (explicit current default behaviour).
  * ``"prefer"``               -> wrapper passes ``--inode-file-handles=prefer``
                                  (recommended; the new default).
  * ``"mandatory"``            -> wrapper passes ``--inode-file-handles=mandatory``
                                  (fails to start on filesystems without
                                  handle support; not recommended unless
                                  every fs is verified).
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from loguru import logger as log

from ..commands import CommandManager

VALID_MODES = ('never', 'prefer', 'mandatory')
DEFAULT_VIRTIOFSD_BINARY = '/usr/libexec/virtiofsd'
# Wrapper filenames are mode-suffixed so VMs that ask for different modes
# (e.g. one VM on 'prefer' for A/B testing while others stay on 'never')
# do not collide on a single shared script.
WRAPPER_BASENAME_TEMPLATE = 'virtiofsd-wrapper-{mode}.sh'
ALL_WRAPPER_BASENAMES = tuple(
    WRAPPER_BASENAME_TEMPLATE.format(mode=m) for m in VALID_MODES
)


def normalize_mode(value: str | None) -> str:
    """Return one of VALID_MODES, or '' if the value is unset/invalid.

    Centralised so config drift, CLI input, and stored values agree on
    what counts as "wrapper enabled".
    """
    if not value:
        return ''
    v = str(value).strip().lower()
    return v if v in VALID_MODES else ''


def wrapper_path(base_dir: str, mode: str) -> str:
    """Filesystem path to the wrapper script for a specific mode.

    Raises ValueError on an invalid mode so we never produce paths like
    ``virtiofsd-wrapper-.sh``.
    """
    m = normalize_mode(mode)
    if not m:
        raise ValueError(f'invalid virtiofsd inode-file-handles mode: {mode!r}')
    return str(Path(base_dir) / WRAPPER_BASENAME_TEMPLATE.format(mode=m))


def is_managed_wrapper_path(base_dir: str, path: str) -> bool:
    """True iff `path` looks like a wrapper aivm would install under base_dir.

    Used by drift detection so we know whether to leave or remove a
    ``<binary path>`` that points inside base_dir.
    """
    if not path:
        return False
    bd = str(Path(base_dir))
    return any(
        path == str(Path(bd) / name) for name in ALL_WRAPPER_BASENAMES
    )


def desired_binary_path(base_dir: str, mode: str) -> str | None:
    """libvirt ``<binary path='...'>`` to emit for the given mode.

    Returns None when the mode is unset/invalid (meaning: emit no
    ``<binary>`` element at all and let libvirt use its built-in default
    path).
    """
    m = normalize_mode(mode)
    if not m:
        return None
    return wrapper_path(base_dir, m)


def wrapper_content(mode: str, real_binary: str = DEFAULT_VIRTIOFSD_BINARY) -> str:
    """The exact bytes the wrapper script should contain.

    Pure function so tests can assert content without touching the disk.
    """
    m = normalize_mode(mode)
    if not m:
        raise ValueError(f'invalid virtiofsd inode-file-handles mode: {mode!r}')
    return (
        '#!/bin/bash\n'
        '# Generated by aivm. Manual edits will be overwritten on next "aivm vm update".\n'
        '# Injects --inode-file-handles to reduce virtiofsd FD pressure.\n'
        f'exec {real_binary} --inode-file-handles={m} "$@"\n'
    )


def ensure_wrapper_installed(
    base_dir: str, mode: str, *, dry_run: bool = False
) -> str | None:
    """Idempotently install the wrapper at ``<base_dir>/virtiofsd-wrapper.sh``.

    Returns the wrapper path on success, or None if ``mode`` is empty /
    invalid (no wrapper needed).
    """
    m = normalize_mode(mode)
    if not m:
        return None
    target = wrapper_path(base_dir, m)
    desired = wrapper_content(m)
    if dry_run:
        log.info(
            'DRYRUN: would ensure virtiofsd wrapper at {} (mode={})',
            target,
            m,
        )
        return target

    mgr = CommandManager.current()

    read = mgr.run(
        ['cat', target],
        sudo=True,
        check=False,
        capture=True,
        role='read',
        summary=f'Inspect existing virtiofsd wrapper at {target}',
    )
    if read.code == 0 and read.stdout == desired:
        return target

    with tempfile.NamedTemporaryFile(
        'w',
        delete=False,
        suffix='.sh',
        prefix='aivm-virtiofsd-wrapper-',
    ) as f:
        f.write(desired)
        tmp = f.name
    try:
        mgr.run(
            ['install', '-m', '0755', tmp, target],
            sudo=True,
            check=True,
            capture=True,
            role='modify',
            summary=f'Install virtiofsd wrapper at {target}',
            detail=f'inode-file-handles={m}',
        )
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass
    log.info('Installed virtiofsd wrapper at {} (mode={})', target, m)
    return target
